# .github/workflows/generate_m3u.yml
name: Generar M3U desde VODS

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir requests beautifulsoup4

      - name: Generate playlist files
        run: |
          python <<EOF
          import re
          import requests
          from bs4 import BeautifulSoup
          from urllib.parse import unquote
          import json

          # rango de años válido: 1900–2025
          year_pattern = re.compile(r'(19\\d{2}|20[0-2]\\d|2025)')

          base_url = 'http://144.217.70.79/VODS-M/1080P/'
          resp = requests.get(base_url)
          resp.raise_for_status()

          soup = BeautifulSoup(resp.text, 'html.parser')
          m3u_lines = ['#EXTM3U']
          records = []

          for link in soup.find_all('a', href=True):
              href = link['href']
              if not href.lower().endswith('.mkv'):
                  continue

              video_url = base_url + href
              raw = unquote(href.rsplit('/', 1)[-1].rsplit('.', 1)[0])

              # buscar todos los años válidos
              years = year_pattern.findall(raw)
              anio = years[-1] if years else ""
              name = raw
              if anio:
                  # quitar año final, con o sin paréntesis
                  # coincide ' 2021', '(2021)', ' 2021)'
                  name = re.sub(r'\\s*\?' + re.escape(anio) + r'\?\\s*$', '', raw).strip()

              # M3U entry
              m3u_lines.append(f'#EXTINF:-1 tvg-name="" tvg-id="" tvg-logo="" group-title="",{raw}')
              m3u_lines.append(video_url)

              # JSON record: sample.name limpio, sample.url y anio
              record = {
                  "name": "",
                  "samples": [{
                      "name": name,
                      "url": video_url,
                      "icono": "",
                      "iconoHorizontal": "",
                      "iconpng": "",
                      "type": "PELICULA",
                      "descripcion": "",
                      "anio": anio,
                      "genero": "",
                      "duracion": ""
                  }]
              }
              records.append(record)

          # escribir archivos
          with open('playlist.m3u', 'w') as f:
              f.write("\\n".join(m3u_lines))
          with open('playlist.json', 'w', encoding='utf-8') as f:
              json.dump(records, f, indent=4, ensure_ascii=False)
          EOF

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u playlist.json
          if ! git diff --cached --exit-code; then
            git commit -m "Actualizar playlist.m3u y playlist.json"
            git push
          else
            echo "No hay cambios"
          fi
